import type { Question } from '../../types'

export const javaQuestions: Question[] = [
  {
    id: 'java-fund-q1',
    question: 'Is Java pass-by-value or pass-by-reference?',
    shortAnswer:
      'Always pass-by-value. For objects, the value passed is a copy of the reference — so reassigning the parameter never affects the caller, but mutating the object through it does.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Basic',
    seniority: 'Mid',
    tags: ['references', 'pass-by-value'],
  },
  {
    id: 'java-fund-q2',
    question: 'Is a class with private fields and public getters/setters properly encapsulated?',
    shortAnswer:
      'Not necessarily. Encapsulation is about controlling state and protecting invariants, not simply hiding fields — a setter with no validation is barely different from a public field.',
    detailedAnswer:
      'Real encapsulation means the class enforces its own invariants: state can only change through methods that guarantee the object never becomes invalid. Getters and setters are the mechanical form; whether they actually protect anything depends on whether they validate.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['encapsulation'],
  },
  {
    id: 'java-fund-q3',
    question: 'How is abstraction different from encapsulation?',
    shortAnswer:
      'Abstraction hides complexity behind a simpler contract (what an object does); encapsulation protects internal state from corruption (how it\'s guarded). A class can have one without the other.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Mid',
    tags: ['abstraction', 'encapsulation'],
  },
  {
    id: 'java-fund-q4',
    question: 'You inherit a codebase where changing an internal detail of a base class keeps unexpectedly breaking subclasses. What\'s this called, and what\'s the fix?',
    shortAnswer:
      'The fragile base class problem — subclasses are coupled to the parent\'s implementation, not just its contract. Refactor toward composition: extract the shared behavior into a collaborator the classes hold a reference to instead of extending.',
    seniorFollowUps: ['How would you migrate an existing inheritance hierarchy to composition without a big-bang rewrite?'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['inheritance', 'composition', 'design'],
  },
  {
    id: 'java-fund-q5',
    question: 'When is inheritance still the right call over composition?',
    shortAnswer:
      'When the relationship is a genuine, Liskov-substitutable "is-a" and you specifically need callers to treat every subtype polymorphically through the parent type — composition alone can\'t give you that without also defining an interface.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Lead',
    tags: ['inheritance', 'composition', 'design'],
  },
  {
    id: 'java-fund-q6',
    question: 'What does the Liskov Substitution Principle forbid, with a concrete example?',
    shortAnswer:
      'A subclass being unusable wherever its parent is expected. Classic case: Square extends Rectangle — overriding setWidth/setHeight to keep width==height breaks any caller that sets them independently expecting predictable area.',
    keyPoints: ['"Is-a" in the English sense isn\'t enough — the subclass must honor every behavioral contract, not just the structural shape'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['solid', 'liskov', 'design'],
  },
  {
    id: 'java-fund-q7',
    question: 'What\'s the real difference between overloading and overriding, in terms of when it\'s resolved?',
    shortAnswer:
      'Overloading is resolved at compile time from the static (declared) type of the arguments. Overriding is resolved at runtime from the object\'s actual type — that\'s the mechanism behind true polymorphism.',
    seniorFollowUps: ['If a method is overloaded with both a supertype and subtype parameter, which one runs when you pass an object whose static type differs from its runtime type?'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Mid',
    tags: ['overloading', 'overriding', 'polymorphism'],
  },
  {
    id: 'java-fund-q8',
    question: 'Does dynamic dispatch apply to field access the same way it applies to method calls?',
    shortAnswer:
      'No. Field access is resolved statically by the reference\'s declared type; only method calls use the object\'s actual runtime type. A common trick question in "what does this print" snippets involving field shadowing.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['dynamic-dispatch', 'polymorphism'],
  },
  {
    id: 'java-fund-q9',
    question: 'After Java 8 added default methods, what actually still distinguishes an interface from an abstract class?',
    shortAnswer:
      'State. An interface still cannot declare instance fields, so it can never carry shared mutable state — only shared default behavior. An abstract class can hold both.',
    detailedAnswer:
      'Use an interface for a capability a type can implement alongside unrelated other interfaces (a class can implement many). Use an abstract class when subclasses genuinely need to share mutable state or a behavior template, since Java only allows single class inheritance.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['interfaces', 'abstract-classes', 'java8'],
  },
  {
    id: 'java-fund-q10',
    question: 'Two interfaces a class implements each declare a default method with the same signature. What happens?',
    shortAnswer:
      'Compile error — Java refuses to silently pick one. The implementing class must override the method explicitly, optionally delegating via InterfaceName.super.method(). This is Java\'s answer to the multiple-inheritance diamond problem.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['interfaces', 'diamond-problem'],
  },
  {
    id: 'java-fund-q11',
    question: 'What breaks if you override equals() but not hashCode()?',
    shortAnswer:
      'Two "equal" objects can land in different HashMap/HashSet buckets, so get()/contains() silently fail to find an entry that logically exists — no exception, just wrong behavior.',
    keyPoints: ['hashCode() picks the bucket; equals() only disambiguates within it', 'Fields used in the contract should be immutable, or an object can become unfindable after mutation'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Mid',
    tags: ['equals-hashcode', 'collections'],
  },
  {
    id: 'java-fund-q12',
    question: 'You put a custom Point object into a HashSet, then create a "new" Point with the same x/y and check `set.contains(newPoint)` — it returns false even though the fields match. Why, and what\'s missing?',
    shortAnswer:
      'HashSet uses hashCode() and equals() to check membership, and the class never overrode either — so it\'s using Object\'s default implementations, which compare references, not field values. Two Points with identical x/y are still different objects with different identity, so contains() correctly reports "not found" by that definition.',
    detailedAnswer:
      'This is exactly why classes meant to be used as values — compared for what they represent, not which specific instance they are — need to override equals()/hashCode() together. Without it, every object-contract-based collection (HashSet, HashMap keys, contains(), etc.) silently falls back to identity comparison.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Mid',
    tags: ['equality', 'equals-hashcode', 'collections'],
  },
  {
    id: 'java-fund-q13',
    question: 'Can a static method be overridden?',
    shortAnswer:
      'No — it can be hidden by a same-signature static method in a subclass, but that\'s resolved at compile time by the reference type, not runtime polymorphic dispatch like an overridden instance method.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['static', 'polymorphism'],
  },
  {
    id: 'java-fund-q14',
    question: 'Why does immutability matter specifically for concurrency?',
    shortAnswer:
      'An immutable object has no mutable state to race on — it can be freely shared across threads with zero synchronization, because it can never be observed in an inconsistent, half-updated state.',
    seniorFollowUps: ['Does declaring a field `final` make the object it references immutable?'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['immutability', 'concurrency'],
  },
  {
    id: 'java-fund-q15',
    question: 'Give a real example of an Open/Closed Principle violation you\'d flag in code review.',
    shortAnswer:
      'A growing if/else or switch on type that needs a new branch every time a new case is added. The Strategy pattern (polymorphism through an interface) usually fixes it by letting new cases be added as new classes instead of edited branches.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['solid', 'design'],
  },
  {
    id: 'java-fund-q16',
    question: 'What\'s the difference between dependency injection and dependency inversion?',
    shortAnswer:
      'Dependency inversion is the principle: high-level modules should depend on abstractions, not concrete implementations. Dependency injection is the mechanism that supplies those abstractions from outside (constructor/setter/framework) instead of the class constructing them itself.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Lead',
    tags: ['solid', 'dependency-injection', 'design'],
  },
  {
    id: 'java-fund-q17',
    question: 'How do you avoid over-engineering "extensibility" that nobody actually needs?',
    shortAnswer:
      'Don\'t add a seam (interface, strategy, plugin point) until there\'s a real, current need for variation. Speculative flexibility adds indirection and cost with no payoff — and is itself a design smell.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Lead',
    tags: ['design', 'over-engineering'],
  },
  {
    id: 'java-fund-q18',
    question: 'Design a small class hierarchy for payment methods (credit card, bank transfer, wallet) in a checkout system. Interface, abstract class, or composition — and why?',
    shortAnswer:
      'A PaymentMethod interface for the contract (charge(), refund()), implemented by each concrete type — payment methods don\'t share meaningful mutable state, so an abstract class would only add coupling with no benefit. If some logic genuinely repeats (retry/backoff), pull it into a shared collaborator via composition, not a base class.',
    seniorFollowUps: ['How would this design change if you later need to add logging or fraud-checking around any payment method?'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Lead',
    tags: ['design', 'interfaces', 'composition'],
  },
  {
    id: 'java-str-q1',
    question: 'You pass a String into a method that appears to modify it, but the caller\'s variable is unchanged. Why?',
    shortAnswer:
      'String is immutable — every "modifying" method (concat, replace, toUpperCase, etc.) returns a new String rather than mutating the original. If the method doesn\'t reassign and return the result, the caller never sees a change.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Basic',
    seniority: 'Mid',
    tags: ['immutability'],
  },
  {
    id: 'java-str-q2',
    question: 'Why does `new String("hi") == "hi"` evaluate to false, but `"hi" == "hi"` evaluate to true?',
    shortAnswer:
      'Two identical literals are both resolved to the same pooled object at compile time, so == (reference equality) holds. `new String(...)` explicitly forces a fresh heap allocation outside that pooled reference, so == fails even though the content is identical.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Basic',
    seniority: 'Mid',
    tags: ['string-pool', 'equality'],
  },
  {
    id: 'java-str-q3',
    question: 'Since Java 7 moved the string pool into the heap, what practical problem did that actually fix?',
    shortAnswer:
      'Before Java 7 the pool lived in PermGen, a small fixed-size space — heavy literal/intern() usage could exhaust it and throw OutOfMemoryError: PermGen space independent of how much heap was actually free. Moving the pool to the heap ties its size to normal heap capacity and makes it subject to standard GC.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['string-pool', 'jvm', 'memory'],
  },
  {
    id: 'java-str-q4',
    question: 'A service parses a 500MB file into memory, then extracts thousands of tiny substrings and discards the original. On an older JVM this held onto huge amounts of memory. On a current JVM it doesn\'t. Why?',
    shortAnswer:
      'Pre-Java 7, substring() shared the original char array and just changed the offset/length — every extracted substring kept the entire original array reachable. Java 7+ always copies only the needed characters, so the original becomes eligible for GC once nothing else references it.',
    seniorFollowUps: ['If you were stuck supporting an app on a pre-Java-7 JVM, how would you work around this without changing the JVM version?'],
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['substring', 'memory', 'jvm'],
  },
  {
    id: 'java-str-q5',
    question: 'When would you actually reach for String.intern() in production code, versus leaving it alone?',
    shortAnswer:
      'When you\'re holding a large number of runtime-built strings with heavy duplication — e.g. parsed tokens from a huge log or dataset — where collapsing duplicates to one pooled reference meaningfully reduces memory. It\'s not a default habit: intern() has its own lookup and pool-growth cost, so it should follow profiling, not precede it.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['string-pool', 'intern', 'performance'],
  },
  {
    id: 'java-str-q6',
    question: 'A code reviewer flags `result += line;` inside a loop processing 100,000 lines. What\'s the actual cost, and what\'s the fix?',
    shortAnswer:
      'Each += allocates a new String (Strings are immutable), copying everything accumulated so far — that\'s O(n²) total work across n iterations, not O(n). Replace with a single StringBuilder and append() inside the loop, building once and calling toString() at the end.',
    detailedAnswer:
      'The compiler can optimize a single expression like `a + b + c` into one StringBuilder automatically, but it cannot do that across separate loop iterations — each iteration\'s += is its own independent allocate-and-copy.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Intermediate',
    seniority: 'Mid',
    tags: ['performance', 'stringbuilder'],
  },
  {
    id: 'java-str-q7',
    question: 'Why does StringBuffer still exist in the JDK given that StringBuilder is recommended almost everywhere?',
    shortAnswer:
      'Legacy compatibility — StringBuffer predates StringBuilder (added in Java 5 specifically to offer an unsynchronized alternative). StringBuffer\'s per-method synchronization is rarely the right concurrency tool anyway: it only makes individual method calls atomic, not multi-step sequences of them, so code that actually needs thread-safety across several operations still needs external locking regardless.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['stringbuilder', 'stringbuffer', 'concurrency'],
  },
  {
    id: 'java-str-q8',
    question: 'A log line renders emoji as two garbled characters instead of one when you print `s.charAt(i)` in a loop. What\'s going on?',
    shortAnswer:
      'The emoji is outside the Basic Multilingual Plane, so it\'s represented as a surrogate pair — two 16-bit chars for one Unicode code point. Iterating by char index (charAt/length) treats each half of the pair as a separate "character." Iterate by code point (codePoints(), codePointAt) instead when correctness with extended Unicode matters.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['unicode', 'surrogate-pairs'],
  },
  {
    id: 'java-str-q9',
    question: 'A file upload works fine locally but produces corrupted text once deployed to a different server. The code calls `new String(bytes)` with no other arguments. What\'s the likely cause?',
    shortAnswer:
      'Omitting the Charset makes String use the JVM\'s platform default encoding, which can differ between the local machine and the deployment environment (e.g. UTF-8 vs a legacy default). Always pass an explicit charset — normally StandardCharsets.UTF_8 — on both getBytes() and the String(byte[], Charset) constructor.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['charset', 'encoding', 'production'],
  },
  {
    id: 'java-str-q10',
    question: 'CSV parsing code using `line.split(",")` silently loses the last column whenever it\'s empty. Why, and how do you fix it?',
    shortAnswer:
      'split() drops trailing empty strings from the result by default. Passing a negative limit — split(",", -1) — preserves them. This is a common, silent CSV/TSV parsing bug precisely because it only shows up when the *last* field happens to be empty.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Intermediate',
    seniority: 'Mid',
    tags: ['split', 'regex', 'gotcha'],
  },
  {
    id: 'java-str-q11',
    question: 'A validation method calling `input.matches(regex)` inside a hot request path shows up in a profiler. Why, and what\'s the fix?',
    shortAnswer:
      'String.matches() compiles the regex into a Pattern internally on every single call — fine for one-off use, wasteful when called repeatedly with the same pattern. Compile the Pattern once as a static final field and reuse Matcher instances from it instead.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['regex', 'performance', 'pattern'],
  },
  {
    id: 'java-str-q12',
    question: 'Why do password/secret-handling APIs (like javax.crypto or KeyStore) take a char[] instead of a String?',
    shortAnswer:
      'A String is immutable and may sit in the string pool indefinitely — there\'s no way to force its backing data to be overwritten in memory. A char[] can be explicitly zeroed out (Arrays.fill) the moment the secret is no longer needed, limiting how long it\'s exposed in a memory dump or swap.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['security', 'immutability'],
  },
  {
    id: 'java-str-q13',
    question: 'Two equal Strings are guaranteed to have the same hashCode() — why does that matter beyond correctness?',
    shortAnswer:
      'Because String caches its hashCode() after computing it once (immutability guarantees it can never go stale), repeated HashMap/HashSet lookups on the same String key reuse the cached value instead of rescanning every character — part of why String is such a fast, popular map key.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['hashcode', 'performance', 'collections'],
  },
  {
    id: 'java-str-q14',
    question: 'When would `String.format()` be the wrong choice even though it\'s more readable than manual concatenation?',
    shortAnswer:
      'In a hot loop or high-throughput path — format() re-parses the format string on every call, which is measurably slower than StringBuilder.append() calls. Readability wins for one-off or low-frequency formatting; raw throughput favors StringBuilder.',
    topic: 'java',
    subtopic: 'strings',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['string-format', 'performance'],
  },
  {
    id: 'java-fund-q19',
    question: 'What can go wrong when a constructor calls an overridable method?',
    shortAnswer:
      'The override can run on the subclass instance before the subclass\'s own field initializers have executed, so it operates on partially-built state — often silently reading defaults (0/null) instead of the values the subclass constructor was about to set.',
    detailedAnswer:
      'Construction order is: superclass constructor runs first, then subclass field initializers, then subclass constructor body. If the superclass constructor calls an overridable method and the subclass overrides it, that override executes during step one — before step two has run. Any subclass field it reads is still at its default value.',
    seniorFollowUps: ['How would you refactor a constructor that needs subclass-specific setup without this hazard?'],
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['constructor', 'inheritance', 'gotcha'],
  },
  {
    id: 'java-fund-q20',
    question: 'Why do wait() and notify() live on Object instead of Thread?',
    shortAnswer:
      'Because every object in Java has an intrinsic lock (monitor), not just Thread instances — wait/notify coordinate threads through whichever object\'s monitor a synchronized block uses, so the methods have to be available on every object, not one special class.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Advanced',
    seniority: 'Senior',
    tags: ['object-class', 'concurrency'],
  },
  {
    id: 'java-fund-q21',
    question: 'What does the Interface Segregation Principle actually forbid, and what does violating it look like in practice?',
    shortAnswer:
      'Forcing a class to implement methods it doesn\'t need just because they\'re bundled into one fat interface. In practice: a Worker interface with work() and eat() that a RobotWorker is forced to implement eat() for, usually with a UnsupportedOperationException or empty stub — a sign the interface should be split.',
    topic: 'java',
    subtopic: 'fundamentals',
    difficulty: 'Intermediate',
    seniority: 'Senior',
    tags: ['solid', 'interfaces', 'design'],
  },
{
  id: 'java-java8-q1',
  question: 'A method takes a Runnable and you pass `() -> counter++` where counter is a local int. It won\'t compile. Why, and what\'s the idiomatic fix?',
  shortAnswer:
    'Lambdas can only capture local variables that are final or effectively final — counter++ reassigns it, so it fails that check. Wrap it in an AtomicInteger (or a single-element array) so the lambda captures a reference whose internal state can change, rather than trying to reassign the captured variable itself.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['lambdas', 'variable-capture'],
},
{
  id: 'java-java8-q2',
  question: 'What actually distinguishes a functional interface from any other interface with default methods?',
  shortAnswer:
    'Exactly one abstract method, full stop — default and static methods, and Object\'s public methods redeclared, don\'t count toward that total. An interface with two default methods and one abstract method is still a valid lambda target; two abstract methods makes it invalid regardless of how many defaults it also has.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['functional-interfaces'],
},
{
  id: 'java-java8-q3',
  question: 'You have `Function<String,String> f = String::toUpperCase;` — is this a bound or unbound method reference, and what does it mean for how f is invoked?',
  shortAnswer:
    'Unbound — the receiver isn\'t fixed at reference-creation time, so the first argument passed to f.apply(x) becomes the object toUpperCase() is called on. f.apply("hi") returns "HI". Contrast with a bound reference like someString::toUpperCase, which ignores any argument and always operates on someString.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['method-references'],
},
{
  id: 'java-java8-q4',
  question: 'Two interfaces a class implements both provide a default `describe()` method — what actually happens, and how do you resolve it?',
  shortAnswer:
    'Compile error — Java refuses to guess which default wins. The implementing class must override describe() explicitly, optionally delegating to one via InterfaceA.super.describe(). This is unrelated to Java 8-specific stream/lambda mechanics but is exactly the diamond-avoidance mechanism default methods introduced.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['default-methods', 'interfaces'],
},
{
  id: 'java-java8-q5',
  question: 'A teammate writes `list.stream().filter(x -> expensiveCheck(x));` with no terminal operation and is confused why expensiveCheck() never runs. Explain why, precisely.',
  shortAnswer:
    'Intermediate operations like filter() are lazy — they just record a pipeline stage, they don\'t execute anything. Nothing runs until a terminal operation (collect, forEach, count, etc.) is called, which pulls elements through the whole chain. Without one, the pipeline is built but never executed.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['streams', 'laziness'],
},
{
  id: 'java-java8-q6',
  question: 'You call `.stream()` on the same List twice inside one method and both work fine, but calling `.forEach()` twice on the same Stream reference throws IllegalStateException. Why isn\'t this a contradiction?',
  shortAnswer:
    'The List is reusable storage — .stream() creates a fresh, independent Stream from it each time. A Stream itself is not reusable: once a terminal operation runs, that specific Stream instance is consumed and any further operation on it throws IllegalStateException. Get a new stream from the source instead of trying to reuse one.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['streams', 'gotcha'],
},
{
  id: 'java-java8-q7',
  question: 'You have a List<List<Integer>> and need a single flat List<Integer> of all values. Why won\'t plain map() get you there?',
  shortAnswer:
    'map() is strictly 1-to-1 — mapping each inner List<Integer> through a function still leaves you with a Stream of some mapped value per inner list, not a flat stream of ints. flatMap(List::stream) replaces each inner list with its own stream of elements and flattens them all into one combined stream.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['streams', 'flatmap'],
},
{
  id: 'java-java8-q8',
  question: 'Why does the no-identity overload of reduce() return Optional<T> while the identity-supplied overload returns T directly?',
  shortAnswer:
    'Without an identity value, reducing an empty stream has no meaningful result to fall back to — Optional models that absence honestly. With an identity supplied, that identity itself serves as the result for an empty stream, so there\'s always a concrete T to return, no wrapping needed.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['streams', 'reduce', 'optional'],
},
{
  id: 'java-java8-q9',
  question: 'Collectors.toMap() throws IllegalStateException in production because two elements produce the same key. What are the two ways to fix this, and what\'s the tradeoff?',
  shortAnswer:
    'Either supply a merge function as the third argument (e.g. (a, b) -> a to keep the first, or a combining function to merge both) or change the key extractor so keys are actually unique. The merge function is a deliberate choice about what "collision" should mean for your data — silently picking one without thinking about it can quietly drop real data.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['collectors', 'streams'],
},
{
  id: 'java-java8-q10',
  question: 'You need to group a List<Employee> by department and get the average salary per department in one pass. What\'s the idiomatic way, without writing a manual loop with a HashMap?',
  shortAnswer:
    'Collectors.groupingBy(Employee::getDepartment, Collectors.averagingDouble(Employee::getSalary)) — groupingBy takes a downstream Collector as a second argument, which lets you aggregate within each bucket in the same pass instead of grouping first and then iterating the resulting Map to compute averages separately.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['collectors', 'groupingBy'],
},
{
  id: 'java-java8-q11',
  question: 'A junior engineer converts a hot-path sequential stream to parallelStream() to "make it faster" and the service starts timing out intermittently elsewhere. What likely went wrong?',
  shortAnswer:
    'parallelStream() uses the JVM-wide common ForkJoinPool by default, sized to the number of CPU cores. If the parallel stream\'s work blocks (I/O, network calls) or the collection is small enough that fork/join overhead dominates, it can starve every other unrelated parallel stream and CompletableFuture in the JVM competing for that same small pool — a systemic issue, not a local one.',
  seniorFollowUps: ['How would you run CPU-bound parallel work without risking starving the common pool used elsewhere in the app?'],
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['parallel-streams', 'performance', 'production'],
},
{
  id: 'java-java8-q12',
  question: 'Why is `optional.orElse(computeExpensiveDefault())` a subtle performance bug even when the Optional is present nearly every time?',
  shortAnswer:
    'orElse() unconditionally evaluates its argument every single call, present or not, because Java evaluates method arguments eagerly before the call. computeExpensiveDefault() runs even on the fast path where its result is discarded. orElseGet(() -> computeExpensiveDefault()) defers the computation to only when actually needed.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['optional', 'performance', 'gotcha'],
},
{
  id: 'java-java8-q13',
  question: 'A code reviewer flags a class with a field of type `Optional<String> middleName`. What\'s the concern, and what should it be instead?',
  shortAnswer:
    'Optional wasn\'t designed as a field/parameter type — it\'s not Serializable, adds an allocation and indirection layer for no real safety benefit as a field, and its whole value proposition is signaling absence at a method return boundary. Use a plain nullable String field (with clear null-handling conventions) instead, and reserve Optional for return types of accessor methods if the API benefits from it.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['optional', 'design'],
},
{
  id: 'java-java8-q14',
  question: 'A service persists user event timestamps as LocalDateTime, and now that it\'s deployed across two regions, event ordering across regions looks wrong. What\'s the root cause?',
  shortAnswer:
    'LocalDateTime carries no time zone — "2024-03-15T14:30" is genuinely ambiguous in absolute terms; the same stored value corresponds to a different real-world instant depending on which region\'s server wrote it. Events should be stored as Instant (or an explicit UTC-anchored type) so every region\'s timestamp is directly comparable, converting to a ZonedDateTime only for display.',
  seniorFollowUps: ['How would you migrate an existing LocalDateTime column safely without losing historical ordering?'],
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Staff',
  tags: ['java.time', 'production', 'design'],
},
{
  id: 'java-java8-q15',
  question: 'Why was SimpleDateFormat historically dangerous as a shared static field, and how does DateTimeFormatter avoid the same problem?',
  shortAnswer:
    'SimpleDateFormat is mutable and stateful internally — concurrent format()/parse() calls on a shared instance corrupt each other\'s internal state with no exception, just wrong output. DateTimeFormatter is immutable, so multiple threads calling it concurrently is inherently safe with zero synchronization needed.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['java.time', 'concurrency'],
},
{
  id: 'java-java8-q16',
  question: 'Compare Stream.reduce() and Collectors.collect() as ways to accumulate results — when would you reach for collect() instead of reduce()?',
  shortAnswer:
    'reduce() is meant for combining immutable values into a single immutable result (sum, max, string via concatenation of immutables) — using it to build a mutable container like a List means creating and discarding intermediate containers repeatedly, which is inefficient and awkward in parallel. collect() is designed exactly for accumulating into a mutable result container (supplier + accumulator + combiner), which is why it, not reduce(), is what backs toList/toMap/groupingBy.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['streams', 'reduce', 'collect'],
},
{
  id: 'java-java8-q17',
  question: 'A pipeline uses `.peek(x -> auditLog.add(x))` to build an audit trail as a side effect, and some entries are mysteriously missing in production. What\'s wrong with relying on peek() this way?',
  shortAnswer:
    'peek() is documented as intended for debugging visibility, not for real application logic — the JVM is permitted to elide calling it for elements the terminal operation doesn\'t actually need (e.g. certain short-circuiting or count() cases where the source size is already known). Side effects meant to reliably happen for every element belong in forEach() or the collector logic itself, not peek().',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Staff',
  tags: ['streams', 'peek', 'gotcha'],
},
{
  id: 'java-java8-q18',
  question: 'When is a plain for-loop still the better engineering choice over an equivalent stream pipeline?',
  shortAnswer:
    'When you need multiple related running aggregates in a single pass, complex conditional branching that would force nested lambdas, or operations that throw checked exceptions (which don\'t compose cleanly inside a functional interface). A nine-stage stream chain crammed to avoid "using a loop" is often a readability regression, not an improvement — streams are a tool for the common transform/filter/collect shape, not a mandate.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Lead',
  tags: ['streams', 'design', 'readability'],
},
{
  id: 'java-java8-q19',
  question: 'A method inside a stream lambda needs to throw a checked IOException, but Function<T,R>.apply() doesn\'t declare any checked exceptions. What are your realistic options?',
  shortAnswer:
    'Wrap the checked exception in an unchecked one inside the lambda (e.g. catch and rethrow as UncheckedIOException), write a small helper that adapts a checked-throwing lambda to the functional interface, or avoid the stream for that step and use a plain loop where the checked exception can be declared normally. There\'s no way to make a standard java.util.function interface declare a checked exception without writing your own functional interface.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['streams', 'lambdas', 'exceptions'],
},
{
  id: 'java-java8-q20',
  question: 'What\'s the practical difference between IntStream and Stream<Integer>, beyond just "one is primitive"?',
  shortAnswer:
    'IntStream avoids boxing every element into an Integer object, which matters for both memory and CPU in large numeric pipelines, and it exposes numeric-specific terminal operations (sum, average, max, summaryStatistics) that a generic Stream<Integer> doesn\'t have, since Stream has no built-in notion of "numeric." mapToInt/boxed() convert between the two when needed.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['streams', 'primitive-streams', 'performance'],
},
{
  id: 'java-java8-q21',
  question: 'A List<Order> needs to become a Map<CustomerId, List<Order>> grouping each customer\'s orders. Walk through the Collector you\'d use and why not toMap().',
  shortAnswer:
    'Collectors.groupingBy(Order::getCustomerId) — toMap() maps each key to exactly one value and throws on a duplicate key, but here every customer legitimately has many orders sharing one key. groupingBy is built for exactly this one-to-many bucketing case, defaulting to List as the downstream container.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['collectors', 'groupingBy', 'toMap'],
},
{
  id: 'java-java8-q22',
  question: 'Since interfaces can now have default and static methods, why do we still need abstract classes at all for Java 8+ code?',
  shortAnswer:
    'Interfaces still cannot declare instance fields, so they can never hold shared mutable state — only shared default behavior operating on values passed in or accessed via other interface methods. An abstract class can hold real shared state across subclasses. Default methods closed the gap on shared *behavior*, not shared *state*.',
  topic: 'java',
  subtopic: 'java8',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['default-methods', 'interfaces', 'abstract-classes'],
},
{
  id: 'java-coll-q1',
  question: 'A hot path does frequent insertions at the front of a large List. Someone suggests switching from ArrayList to LinkedList. Do you agree?',
  shortAnswer:
    'Only if profiling actually shows the shift cost dominating — LinkedList\'s O(1) head insert avoids ArrayList\'s O(n) shift, but LinkedList pays for it with per-node pointer overhead and worse cache locality everywhere else. Often the better fix is ArrayDeque (if order allows) or restructuring to append at the end instead.',
  detailedAnswer:
    'In practice, ArrayList\'s contiguous memory makes even its O(n) operations fast in wall-clock terms for moderate sizes due to cache locality, while LinkedList\'s O(1) claims come with constant-factor overhead (object headers, pointer chasing) that often loses for real workloads. Measure before switching.',
  seniorFollowUps: ['What data structure would you reach for if you needed O(1) at both ends and O(1) random access?'],
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['arraylist', 'linkedlist', 'performance'],
},
{
  id: 'java-coll-q2',
  question: 'Why does the JDK documentation recommend ArrayDeque over both LinkedList and the legacy Stack class for stack/queue use?',
  shortAnswer:
    'ArrayDeque is backed by a contiguous circular array, giving it better cache locality and lower per-element overhead than LinkedList\'s node pointers. Stack additionally extends the legacy, fully-synchronized Vector, paying locking overhead even in single-threaded code.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['arraydeque', 'stack', 'performance'],
},
{
  id: 'java-coll-q3',
  question: 'You put custom Point objects into a HashSet, then mutate the x field of an object already in the set. contains() with an equal object now returns false. What happened?',
  shortAnswer:
    'HashSet placed the object into a bucket based on its hashCode() at insertion time. Mutating a field the hashCode() depends on doesn\'t move the object to a new bucket — it\'s now "stuck" in the wrong one, and a fresh lookup computes a different bucket than where it actually lives, so it silently can\'t be found.',
  keyPoints: ['This is why keys used in hash-based collections should be immutable, or at least never mutated in fields that participate in equals()/hashCode()'],
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['hashset', 'hashcode', 'gotcha'],
},
{
  id: 'java-coll-q4',
  question: 'Walk through what actually happens internally when you call HashMap.get(key) — from the key\'s hashCode() to the returned value.',
  shortAnswer:
    'The key\'s hashCode() is computed and spread (XORed with its own upper bits) to reduce clustering, then masked against (capacity-1) to pick a bucket index. Within that bucket, entries are scanned using equals() to find the matching key (a short chain, or a red-black tree if the bucket was treeified), and that entry\'s value is returned.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['hashmap', 'internals'],
},
{
  id: 'java-coll-q5',
  question: 'What triggers HashMap bucket treeification, and why was it added in Java 8?',
  shortAnswer:
    'A single bucket accumulating more than 8 entries (with the table capacity at least 64) converts that bucket\'s linked list into a red-black tree, capping worst-case lookup at O(log n) instead of O(n). It was added specifically to defend against pathological or adversarially-crafted hashCode() collisions degrading a HashMap to linked-list-like performance.',
  seniorFollowUps: ['Why is there also a threshold to convert it back to a list, rather than leaving it as a tree once treeified?'],
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['hashmap', 'treeification', 'internals'],
},
{
  id: 'java-coll-q6',
  question: 'A service constructs a HashMap and immediately bulk-inserts 100,000 known entries. A reviewer suggests specifying an initial capacity. Why would that matter?',
  shortAnswer:
    'Without it, the map starts at capacity 16 and resizes (doubles + rehashes every existing entry) repeatedly as it grows past each load-factor threshold — each resize is an O(n) full rehash. Pre-sizing to roughly (expectedEntries / loadFactor) avoids that churn entirely for a known bulk load.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['hashmap', 'load-factor', 'performance'],
},
{
  id: 'java-coll-q7',
  question: 'What\'s the practical difference between HashMap and ConcurrentHashMap beyond "one is thread-safe"?',
  shortAnswer:
    'ConcurrentHashMap uses fine-grained locking (per-bucket in Java 8+, via CAS and synchronized on head nodes) so multiple threads can read and write different parts of the map concurrently, and its iterators are weakly consistent — they never throw ConcurrentModificationException. It also disallows null keys/values to avoid ambiguity under concurrent access, unlike HashMap.',
  detailedAnswer:
    'Wrapping a HashMap with Collections.synchronizedMap gives correctness but locks the entire map on every call, serializing all access even to unrelated keys — a much coarser and slower approach than ConcurrentHashMap\'s design.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['concurrenthashmap', 'concurrency'],
},
{
  id: 'java-coll-q8',
  question: 'You need a simple in-memory LRU cache with a fixed max size. How would you implement it with a single JDK class?',
  shortAnswer:
    'Extend LinkedHashMap constructed with accessOrder=true, and override removeEldestEntry() to return true once size() exceeds the cache limit — the map\'s own linked list already tracks recency, so eviction needs no extra bookkeeping.',
  example:
    'class LruCache<K,V> extends LinkedHashMap<K,V> {\n    private final int max;\n    LruCache(int max) { super(16, 0.75f, true); this.max = max; }\n    protected boolean removeEldestEntry(Map.Entry<K,V> e) { return size() > max; }\n}',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['linkedhashmap', 'lru', 'design'],
},
{
  id: 'java-coll-q9',
  question: 'A for-each loop that calls list.remove(item) mid-iteration throws ConcurrentModificationException — in single-threaded code with no other thread involved. Why, and what\'s the fix?',
  shortAnswer:
    'The list\'s iterator is fail-fast: it tracks a modCount and detects that the collection was structurally modified by something other than the iterator itself, throwing on the next next() call. Fix by using Iterator.remove() directly, or replacing the loop with list.removeIf(predicate).',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['fail-fast', 'concurrentmodificationexception', 'iteration'],
},
{
  id: 'java-coll-q10',
  question: 'How does CopyOnWriteArrayList avoid ConcurrentModificationException, and what\'s the cost of that approach?',
  shortAnswer:
    'Every write (add/remove/set) copies the entire backing array; iterators hold a reference to the snapshot array taken when they were created, so they never observe concurrent structural changes and never throw. The cost is that every single write is an O(n) full array copy, making it a poor fit for write-heavy collections.',
  seniorFollowUps: ['What workload characteristics make CopyOnWriteArrayList the right choice despite that cost?'],
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['copyonwritearraylist', 'concurrency'],
},
{
  id: 'java-coll-q11',
  question: 'A TreeSet<BigDecimal> ends up with fewer elements than expected after adding "1.0" and "1.00" — size() is 1, not 2. Why, given that BigDecimal("1.0").equals(BigDecimal("1.00")) is false?',
  shortAnswer:
    'TreeSet uses compareTo() (BigDecimal\'s natural ordering ignores scale) as its sole notion of "already present," not equals() (which does consider scale). compareTo() says they\'re equal, so the second add() is silently treated as a duplicate and dropped — a well-known compareTo/equals inconsistency trap.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['treeset', 'comparable', 'gotcha'],
},
{
  id: 'java-coll-q12',
  question: 'What\'s the real difference between Comparable and Comparator, and when would a class need both?',
  shortAnswer:
    'Comparable defines one natural ordering baked into the class itself (compareTo). Comparator defines an external, swappable ordering you can pass to sort()/TreeMap/TreeSet without touching the class — useful when you need multiple orderings of the same type, or can\'t modify the class at all (e.g. a third-party type).',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['comparable', 'comparator', 'ordering'],
},
{
  id: 'java-coll-q13',
  question: 'A getter returns Collections.unmodifiableList(this.internalList). A caller reports the "immutable" list they received changed after the fact. What\'s going on, and how do you actually fix it?',
  shortAnswer:
    'unmodifiableList only blocks writes attempted through that specific returned reference — it\'s a thin view over the still-mutable original list, and any code (including the same class) that mutates internalList directly is visible through the view. For a real guarantee, return a defensive copy — List.copyOf(internalList) or new ArrayList<>(internalList) wrapped unmodifiable.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['unmodifiable', 'immutability', 'encapsulation'],
},
{
  id: 'java-coll-q14',
  question: 'What\'s the difference between List.of("a", "b") and Collections.unmodifiableList(new ArrayList<>(List.of("a","b")))?',
  shortAnswer:
    'List.of() produces a genuinely immutable collection — fixed at creation, rejects null elements, throws immediately on any mutation attempt. Collections.unmodifiableList wraps a mutable list in a read-only view; the view itself can\'t be written to, but the underlying list can still change and that change shows through the view.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['list-of', 'unmodifiable', 'immutability'],
},
{
  id: 'java-coll-q15',
  question: 'Why does iterating a PriorityQueue directly with a for-each loop not yield elements in sorted order, when polling one at a time does?',
  shortAnswer:
    'PriorityQueue is a binary heap — it only guarantees the smallest element sits at the root (index 0); the rest of the backing array is merely heap-ordered, not fully sorted. Direct iteration walks the raw array; repeated poll() re-heapifies after each removal, which is what actually produces sorted output.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['priorityqueue', 'heap', 'gotcha'],
},
{
  id: 'java-coll-q16',
  question: 'A design review flags a service using HashMap<String, List<Order>> without synchronization, accessed from multiple request-handling threads. What are your options, in order of preference?',
  shortAnswer:
    'Prefer ConcurrentHashMap<String, List<Order>> with a thread-safe or immutable value list (e.g. building via computeIfAbsent + a CopyOnWriteArrayList, or replacing the whole list atomically on update) over Collections.synchronizedMap, which serializes all access with one coarse lock and still requires manual synchronization for compound operations.',
  seniorFollowUps: ['How would you atomically append to the per-key list without a race between two threads both doing get-then-add on a missing key?'],
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['concurrenthashmap', 'design', 'concurrency'],
},
{
  id: 'java-coll-q17',
  question: 'Why does ConcurrentHashMap disallow null keys and null values, when HashMap allows both?',
  shortAnswer:
    'In a concurrent context, get(key) returning null is ambiguous — it could mean "no mapping exists" or "mapped to null," and a second thread could have removed or added the mapping between a containsKey() check and a get() call, making the distinction unsafely racy to resolve. Disallowing null entirely removes the ambiguity.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['concurrenthashmap', 'null-handling', 'concurrency'],
},
{
  id: 'java-coll-q18',
  question: 'You need to process items in strict insertion order but also check membership in O(1) and never allow duplicates. Which collection, and why not the obvious alternatives?',
  shortAnswer:
    'LinkedHashSet — it gives O(1) average add/contains like HashSet while additionally maintaining insertion order via its internal linked list, at only a modest memory cost. A TreeSet would give sorted, not insertion, order at O(log n); a List would need an O(n) contains() check for uniqueness.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['linkedhashset', 'design'],
},
{
  id: 'java-coll-q19',
  question: 'Arrays.asList(1, 2, 3) is passed to a method that calls list.add(4) on it — this throws UnsupportedOperationException. Why, when it looks like a normal List?',
  shortAnswer:
    'Arrays.asList() returns a fixed-size list backed directly by the array — it supports set() (which writes through to the array) but not structural changes like add/remove, since those can\'t be represented in a fixed-length array. Wrap it in new ArrayList<>(Arrays.asList(...)) if a genuinely resizable list is needed.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['arrays-aslist', 'gotcha'],
},
{
  id: 'java-coll-q20',
  question: 'What\'s the actual cost difference between ArrayList\'s add(element) at the end versus add(index, element) in the middle?',
  shortAnswer:
    'add(element) is O(1) amortized — it just writes to the next free slot, occasionally triggering an O(n) resize. add(index, element) is always O(n) because every element from that index onward must be shifted right by one slot to make room, regardless of whether a resize is also needed.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Intermediate',
  seniority: 'Mid',
  tags: ['arraylist', 'complexity'],
},
{
  id: 'java-coll-q21',
  question: 'A batch job builds a Set<Long> of about 5 million unique IDs by repeated add() calls with the default HashSet constructor. What\'s the likely performance issue, and the one-line fix?',
  shortAnswer:
    'Starting at capacity 16 with load factor 0.75 forces roughly 20 resize-and-rehash cycles as the set grows to 5 million entries, each one an O(n) full rehash of everything inserted so far. Constructing with new HashSet<>((int)(5_000_000 / 0.75) + 1) pre-sizes the table and avoids that churn.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['hashset', 'performance', 'load-factor'],
},
{
  id: 'java-coll-q22',
  question: 'Two engineers disagree: one wants to use a HashMap<String, List<String>> as a multimap, the other wants Guava\'s Multimap. What\'s the actual tradeoff, and what would you check first?',
  shortAnswer:
    'A hand-rolled HashMap<K, List<V>> needs manual computeIfAbsent boilerplate everywhere and is easy to get subtly wrong (empty lists left behind after removal, no built-in flatten/size-across-keys). A dedicated Multimap type handles that consistently and gives you views (asMap, entries) for free — but it\'s an added dependency and a less familiar API to the team. Check whether Guava (or a similar library) is already a dependency before introducing it just for this.',
  topic: 'java',
  subtopic: 'collections',
  difficulty: 'Advanced',
  seniority: 'Staff',
  tags: ['design', 'multimap', 'tradeoffs'],
},
{
  id: 'java-gen-q1',
  question: 'A colleague writes `List<Object> list = new ArrayList<String>();` and it fails to compile. They expected it to work since String is an Object. Why doesn\'t it, and what\'s the actual fix if they need the flexibility they wanted?',
  shortAnswer: 'Generics are invariant — List<String> is not a List<Object> — because allowing it would let you insert a non-String into what\'s really backed by a String array. Use List<? extends Object> (or just Object where read-only access is enough) if they only need to read.',
  detailedAnswer: 'If the assignment compiled, you could then call list.add(42) on what the compiler thinks is List<Object>, but is actually the caller\'s List<String> underneath — a runtime ClassCastException waiting to happen on the next String read. Invariance closes that hole at compile time. The fix depends on intent: if the method only reads elements, declare the parameter as List<? extends Object> (functionally just List<?> here since Object is the top type); if it needs a genuinely polymorphic mutable collection, the design question is why — usually the answer is to not need Object at all and use a proper bound.',
  keyPoints: ['Generics do not mirror reference-type subtyping', 'Invariance is a safety feature, not a limitation to route around carelessly', '? extends fixes the read case; there is no fix that gives back full read+write with a supertype element type'],
  seniorFollowUps: ['How is this different from array covariance, and why did the language make that choice differently for arrays?', 'What would go wrong at runtime if invariance weren\'t enforced?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['generics', 'invariance', 'type-safety'],
},
{
  id: 'java-gen-q2',
  question: 'You\'re reviewing a PR where a method signature is `static <T> void copy(List<? super T> dest, List<? extends T> src)`. A teammate asks why not just `List<T> dest, List<T> src` — simpler, and it would still work for their test case. What do you tell them?',
  shortAnswer: 'The wildcard version is strictly more flexible: it accepts src as a List<Integer> and dest as a List<Number> in the same call, which List<T> for both could never do since it would force identical type arguments. It\'s the PECS pattern — producer extends, consumer super.',
  detailedAnswer: 'With List<T> dest, List<T> src, both parameters are locked to the exact same type argument T — you couldn\'t copy a List<Integer> into a List<Number>, even though that\'s perfectly type-safe (every Integer is a Number). The wildcard signature decouples them: src just needs to produce something assignable to T (? extends T), dest just needs to accept something of type T (? super T). Their test case passing with the simpler signature doesn\'t prove equivalence — it just means their test happened to pass matching types on both sides.',
  keyPoints: ['Get Maximum flexibility from the API rather than from the test case that happens to pass', 'This is exactly Collections.copy\'s real signature', 'Wildcards widen the range of legal call sites without weakening type safety'],
  seniorFollowUps: ['What would you lose if you used List<?> for both instead?', 'Where in java.util.Collections else is this pattern visible?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['generics', 'wildcards', 'pecs', 'api-design'],
},
{
  id: 'java-gen-q3',
  question: 'Why does `List<String>[] arr = new List<String>[10];` fail to compile, but `List[] arr = new List[10];` is fine?',
  shortAnswer: 'Arrays are reified and enforce their element type at every store (ArrayStoreException); a generic array\'s element type is erased at runtime, so the JVM would have no way to enforce or even represent that check — the language forbids creating it outright rather than allow an unsound array.',
  detailedAnswer: 'Arrays remember their component type at runtime and throw ArrayStoreException if you try to store an incompatible element. Generics have no such runtime memory — List<String> and List<Integer> are the same erased type at runtime. If you could create a List<String>[], you could alias it through Object[] and store a List<Integer> into a slot, and there would be zero runtime mechanism to catch it — a silent heap-pollution bug rather than a clean exception. Raw List[] is fine because there\'s no generic type argument being lied about — every element is just "a List", checked as such.',
  keyPoints: ['Arrays: reified, checked at runtime', 'Generics: erased, checked at compile time only', 'Combining the two loses the runtime check without gaining the compile-time one'],
  seniorFollowUps: ['How does the JDK implement something like `toArray()` on a generic collection given this restriction?', 'What is the standard workaround, and what warning does it require suppressing?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['generics', 'type-erasure', 'arrays'],
},
{
  id: 'java-gen-q4',
  question: 'A junior engineer asks why they can\'t write `T create() { return new T(); }` inside a generic class, and how they should build a generic object factory instead.',
  shortAnswer: 'Erasure removes the concrete type of T by runtime, so there\'s no class for new T() to allocate. Instead, accept a Supplier<T> (or a Class<T> token) from the caller and delegate construction to it.',
  detailedAnswer: 'The compiler can\'t emit a `new` bytecode instruction without knowing the exact class, and after erasure T is just Object (or its bound) at runtime — there\'s nothing concrete left to instantiate. The standard fix is dependency injection at the type level: have the caller, who does know the concrete type, hand in either a Supplier<T> lambda (`() -> new Foo()`) or a Class<T> reference and use reflection (Class.getDeclaredConstructor().newInstance()) as a fallback. The Supplier approach is preferred in modern code — no reflection, no checked exceptions to wrangle.',
  keyPoints: ['new T() is a compile error, not a runtime one — the compiler catches it directly', 'Supplier<T> is the idiomatic fix in modern Java', 'Class<T> + reflection is the older, heavier alternative'],
  seniorFollowUps: ['What are the downsides of the reflection-based Class<T> approach in a hot path?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['generics', 'type-erasure', 'factory-pattern'],
},
{
  id: 'java-gen-q5',
  question: 'You inherit a codebase with `@SuppressWarnings("unchecked")` scattered across dozens of methods, some suppressing at the class level. How do you evaluate whether this is a real problem, and how would you clean it up?',
  shortAnswer: 'Unchecked warnings mean the compiler couldn\'t verify a cast or array creation is safe — some are genuinely unavoidable (varargs, array-backed generics) but class-level suppression hides real bugs alongside the fine ones. Narrow every suppression to the smallest scope, verify each one is actually safe, and delete any that turn out to mask an actual erasure-related bug.',
  detailedAnswer: 'Class-level @SuppressWarnings silences every unchecked operation in the class, including ones added later by someone who never intended to suppress anything — that\'s the real risk, not the annotation itself. The cleanup process: move each suppression down to the single statement or local variable that needs it, which forces you to look at each one individually; for each, confirm the underlying cast really is safe (e.g. a Supplier-based Object[] to T[] cast guarded by construction logic) versus one that\'s just papering over an actual type confusion; delete suppressions that no longer apply after refactors. A pile of accumulated unchecked warnings is exactly the kind of place a ClassCastException likes to hide months later.',
  keyPoints: ['Not all unchecked warnings are false alarms — some code really is unsafe', 'Suppress at the narrowest scope possible, always', 'Treat suppression review as a code-quality task, not a nuisance to silence and move on from'],
  seniorFollowUps: ['Give an example of an unchecked cast that is actually safe versus one that isn\'t.'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Staff',
  tags: ['generics', 'unchecked-warnings', 'code-quality'],
},
{
  id: 'java-gen-q6',
  question: 'What is heap pollution, and how can a generic varargs method cause it even with @SafeVarargs applied?',
  shortAnswer: 'Heap pollution is when a variable of a parameterized type ends up referencing an object of a different, incompatible parameterized type — typically via a generic varargs array, which is really a T[] under the hood. @SafeVarargs suppresses the compiler warning; it doesn\'t make unsafe code inside the method safe.',
  detailedAnswer: '`static <T> void f(T... args)` compiles to a T[] parameter, which after erasure is really an Object[] (or the bound\'s array type). If the method itself stores something of the wrong type into that array, or leaks a reference to it that a caller then misuses, you get heap pollution — a slot that claims to be T but isn\'t. @SafeVarargs is a developer promise, checked only superficially by the compiler (it verifies the method doesn\'t do the classic unsafe things like returning the array or storing into it from outside), not a guarantee — a method can still misuse the array internally and heap-pollute despite the annotation, if the "obviously safe" pattern is violated in a non-obvious way.',
  keyPoints: ['Heap pollution: a parameterized-type variable referencing the wrong parameterized type underneath', '@SafeVarargs restricted to static/final/private/constructors — those can\'t be overridden unsafely', 'The annotation documents a promise; it doesn\'t enforce it beyond simple compiler checks'],
  seniorFollowUps: ['Why is @SafeVarargs disallowed on a non-final instance method?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Advanced',
  seniority: 'Staff',
  tags: ['generics', 'varargs', 'heap-pollution'],
},
{
  id: 'java-gen-q7',
  question: 'Compare `List<Object>` and `List<?>` as a method parameter type. When would each be the wrong choice?',
  shortAnswer: 'List<Object> is a real, fully generic type — you can add any Object into it — but a caller\'s List<String> can\'t be passed to it (invariance). List<?> accepts a list of literally any element type but, because that type is unknown, you can\'t add anything into it (except null) — only read as Object.',
  detailedAnswer: 'List<Object> is the wrong choice when you want the method to accept any caller\'s list (List<String>, List<Integer>, etc.) — invariance blocks all of those from binding to List<Object>. List<?> is the wrong choice when the method actually needs to insert elements of a specific type, since the unknown wildcard type makes every add (other than null) a compile error. In practice: use List<?> for read-only utility methods (size, iteration as Object); use a bounded wildcard (? extends X) when you need typed reads; use a type parameter <T> when the method needs to both read and write T consistently.',
  keyPoints: ['List<Object> ≠ "accepts anything" — it only accepts an actual List<Object>', 'List<?> accepts any list but is nearly read-only', 'The right choice depends on whether the method reads, writes, or both'],
  seniorFollowUps: ['Where would a bounded wildcard like List<? extends Number> be strictly better than either of these?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['generics', 'wildcards', 'api-design'],
},
{
  id: 'java-gen-q8',
  question: 'A legacy method returns a raw `List` from a library you don\'t control. What are the concrete risks of assigning it directly to a `List<String>` variable, and how would you defensively handle it?',
  shortAnswer: 'The compiler lets the raw-to-generic assignment through with only an unchecked warning — if the underlying list actually contains non-String elements, you get a ClassCastException later, potentially far from the actual bug. Defensively validate elements at the boundary rather than trusting the raw type.',
  detailedAnswer: 'Assigning a raw List to List<String> compiles with an unchecked warning, not an error — the compiler is trusting you that the library really does return Strings. If that trust is misplaced (a bug in the library, or a contract change), the ClassCastException surfaces wherever the first bad element is actually read as a String, which could be deep in unrelated code, making it hard to trace back to the real source. Defensive handling: at the integration boundary, iterate and cast/validate explicitly (or use a stream with an instanceof filter), so the failure surfaces immediately at the boundary with a clear stack trace rather than silently downstream.',
  keyPoints: ['Raw-to-generic assignment is legal with just a warning, not blocked', 'The resulting ClassCastException can surface far from its actual cause', 'Validate at the trust boundary rather than deferring the check'],
  seniorFollowUps: ['How would Collections.checkedList help here, and what\'s its runtime cost?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Advanced',
  seniority: 'Senior',
  tags: ['generics', 'raw-types', 'legacy-interop'],
},
{
  id: 'java-gen-q9',
  question: 'Explain why `Enum<E>` is declared as `Enum<E extends Enum<E>>`. What breaks if you strip the self-bound down to just `Enum<E>`?',
  shortAnswer: 'The self-bound lets Enum\'s compareTo (and other supertype methods) be typed against the concrete enum subclass E, instead of the generic Enum base. Without it, compareTo would accept any Enum, meaning you could legally compare two completely unrelated enum types, which is never sensible.',
  detailedAnswer: 'With the self-bound `E extends Enum<E>`, when Day implements Enum<Day> (implicitly, via `enum Day`), Comparable\'s compareTo becomes compareTo(Day), not compareTo(Enum). This gives you compile-time protection against comparing a Day to a Color. Without the self-bound, the declaration would just be Enum<E>, and E would only be constrained to "some type" with no relationship back to Enum itself — you could plausibly compare across unrelated enum families and only catch the mistake, if ever, via a nonsensical runtime result. This is the "curiously recurring generic pattern," and it shows up whenever supertype behavior needs to stay typed to the concrete subclass — fluent builder chains that return `this` typed correctly are the other common example.',
  keyPoints: ['Self-bound ties E back to the type extending Enum<E>', 'Prevents comparing across unrelated enum families', 'Same pattern used for fluent builders that need subclass-typed return values'],
  seniorFollowUps: ['Where would you apply this pattern in your own API design, outside of enums?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Advanced',
  seniority: 'Staff',
  tags: ['generics', 'self-bounded-types', 'enum'],
},
{
  id: 'java-gen-q10',
  question: 'You need a method that deserializes JSON into a `List<User>` using a generic JSON library. Passing `List.class` loses the element type entirely. How do libraries like Jackson solve this, given that generics are erased?',
  shortAnswer: 'They use the super type token trick: the caller creates an anonymous subclass of a generic abstract class capturing the full parameterized type (e.g. new TypeReference<List<User>>(){}), and the library reads that off the anonymous subclass\'s reflective generic superclass — information the JVM does retain for class declarations, unlike for erased local type usages.',
  detailedAnswer: 'A bare Class<T> token (List.class) can only express a raw class, never a parameterized type — Class<List<User>> doesn\'t exist as a distinct runtime object separate from Class<List>. The super type token pattern works around this by exploiting that a class\'s generic superclass information is NOT erased — javac records it in the .class file for reflection (getGenericSuperclass()). So `new TypeReference<List<User>>(){}` creates an actual (anonymous) class whose generic superclass is literally TypeReference<List<User>>, and the library reflects on that anonymous subclass to recover the full parameterized type at runtime.',
  keyPoints: ['Class<T> alone cannot represent a parameterized type', 'Generic superclass info on a class declaration survives erasure, unlike local generic usage', 'Anonymous subclassing is the mechanism that exploits this'],
  seniorFollowUps: ['Why does this technique require an anonymous (or otherwise concrete) subclass rather than just instantiating TypeReference directly?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['generics', 'type-erasure', 'reflection', 'super-type-token'],
},
{
  id: 'java-gen-q11',
  question: 'A repository interface in your codebase looks like `interface Repository<T, ID, X, Y>` where X and Y are barely used and every current implementation passes the same two concrete types for them. How would you push back on this design in a code review?',
  shortAnswer: 'Extra type parameters that don\'t vary across real implementations add ceremony without buying flexibility — they should be collapsed to concrete types or dropped, and reintroduced only when a second, genuinely different implementation actually needs them.',
  detailedAnswer: 'Generics are a tool for expressing real variation across call sites — when every current (and foreseeable) implementation instantiates X and Y identically, those parameters aren\'t doing type-safety work, they\'re just noise every reader has to parse through. The review pushback: ask what concrete problem X and Y solve today, not hypothetically; if the answer is "future flexibility," point out that adding a type parameter later, when a second real implementation actually needs it, is a much smaller change than the interface change would suggest — Java lets you generify incrementally far more easily than most engineers assume, especially behind a well-encapsulated interface. YAGNI applies to type parameters just as much as to code.',
  keyPoints: ['A type parameter should track real variation, not speculative flexibility', 'Over-parameterized generics hurt readability at every call site', 'Generifying later is usually cheaper than carrying unused flexibility now'],
  seniorFollowUps: ['What would make you agree the extra parameters are justified?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Staff',
  tags: ['generics', 'api-design', 'over-engineering'],
},
{
  id: 'java-gen-q12',
  question: 'What is a bridge method, and why does the compiler need to generate one when a generic interface method is overridden with a more specific parameter type?',
  shortAnswer: 'A bridge method is a synthetic compiler-generated method that preserves polymorphic dispatch after erasure — when compareTo(T) erases to compareTo(Object) in the interface but the implementation writes compareTo(ConcreteType), the compiler adds a compareTo(Object) override that casts and delegates, so virtual dispatch through the interface reference still finds the right method.',
  detailedAnswer: 'Comparable<Day>.compareTo(T) erases to compareTo(Object) in the interface\'s bytecode. If Day writes `public int compareTo(Day o)`, that\'s a different erased signature (compareTo(Day) vs compareTo(Object)) — from the JVM\'s perspective, without help, Day.compareTo(Day) would not actually override Comparable.compareTo(Object), breaking polymorphism through a Comparable reference. The compiler fixes this by synthesizing a second method, compareTo(Object o) { return compareTo((Day) o); }, which does have the matching erased signature and simply forwards to the type-specific one. This is invisible in source but shows up if you reflectively enumerate a class\'s declared methods.',
  keyPoints: ['Erasure can make an override\'s signature not literally match the interface\'s erased signature', 'Bridge methods reconcile this so polymorphic dispatch still works', 'They are synthetic — generated, not written by hand'],
  seniorFollowUps: ['How would you spot a bridge method if you were debugging via reflection or bytecode inspection?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['generics', 'type-erasure', 'bridge-methods', 'polymorphism'],
},
{
  id: 'java-gen-q13',
  question: 'Two overloaded methods, `void process(List<String> l)` and `void process(List<Integer> l)`, fail to compile in the same class with an erasure clash error. What are the real alternatives to fix this, and which would you pick for a public API?',
  shortAnswer: 'Rename one method, use a single method taking List<?> and branch internally on the element type, or overload on a genuinely different erased type (e.g. accept Collection vs List). For a public API, prefer distinct method names — it\'s clearer to callers and avoids brittle runtime type-checking inside the method.',
  detailedAnswer: 'The two signatures both erase to process(List), which the compiler treats as a duplicate method — this isn\'t a generics-specific rule so much as ordinary method overloading rules applied after erasure. Options: (1) give the methods different names (processStrings/processIntegers) — most readable, no runtime type inspection needed; (2) collapse to a single process(List<?> l) and use instanceof checks inside — works but pushes a type-safety problem back to runtime, which generics exist to avoid; (3) change one parameter\'s erased type (e.g. one takes List, the other Collection) — fragile and confusing. For a public API, distinct names win: callers get compile-time clarity about which behavior they\'re invoking, and the implementation doesn\'t need defensive runtime checks.',
  keyPoints: ['Erasure clash is an ordinary overload-collision rule, just triggered by generics', 'Distinct method names are the cleanest fix for public APIs', 'A single List<?> method trades compile-time safety for runtime type inspection'],
  seniorFollowUps: ['Would your answer change for a private/internal-only method?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['generics', 'type-erasure', 'overloading', 'api-design'],
},
{
  id: 'java-gen-q14',
  question: 'Given `<T extends Comparable<T>> T max(List<T> list)`, a caller wants to call it with a `List<Shape>` where Shape only implements `Comparable<Object>`, not `Comparable<Shape>`. Does it compile, and what does that tell you about writing bounds correctly?',
  shortAnswer: 'It does not compile — T is bound to Comparable<T> exactly, and Shape implementing Comparable<Object> doesn\'t satisfy Comparable<Shape>. The fix, and the general lesson, is to bound against a wildcard when you want to accept a Comparable of any supertype: <T extends Comparable<? super T>>.',
  detailedAnswer: 'The naive bound T extends Comparable<T> requires the exact type T to implement Comparable<T>. A class that implements Comparable<Object> (comparing against any object, a looser but still valid contract) doesn\'t literally satisfy Comparable<T> for T=Shape. The fix used throughout the JDK (Collections.max\'s real signature) is <T extends Comparable<? super T>> — this accepts any Comparable implementation as long as it can compare against T or a supertype of T, which is exactly PECS applied to a bound rather than a wildcard parameter. It\'s a subtle but recurring pattern: bounds need the same producer/consumer thinking as parameter wildcards, not just "the obvious" self-reference.',
  keyPoints: ['T extends Comparable<T> is stricter than it looks — an exact-match requirement', 'T extends Comparable<? super T> is the more permissive, more correct bound', 'This is Collections.max\'s actual declared signature'],
  seniorFollowUps: ['Why doesn\'t the JDK just declare Comparable<T> generically looser in the first place?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Expert',
  seniority: 'Staff',
  tags: ['generics', 'bounded-types', 'pecs', 'comparable'],
},
{
  id: 'java-gen-q15',
  question: 'How would you explain, to someone who only knows that "generics prevent ClassCastException," what actually changed in the bytecode versus what changed only for the compiler between a pre-generics `List` and a modern `List<String>`?',
  shortAnswer: 'Nothing changed in the runtime type or bytecode of List itself — a List<String> is the exact same java.util.List class at runtime as a raw List always was. What changed is entirely compile-time: javac inserts the type check at every add and an invisible cast at every get, and rejects code that would violate T. At runtime, generics are gone — this is type erasure.',
  detailedAnswer: 'Before generics, `List list = ...; String s = (String) list.get(0);` required an explicit, unchecked cast that could fail at runtime if the list held something else. After generics, `List<String> list = ...; String s = list.get(0);` looks cast-free, but the compiler is silently inserting the exact same checkcast bytecode instruction after the call to get() — you just don\'t see it in source. The real value generics add is entirely at compile time: the compiler now refuses to let you add anything but a String into that list in the first place, so the inserted cast becomes provably safe rather than a leap of faith. This is worth internalizing because it explains every other erasure gotcha in one shot: nothing at runtime distinguishes List<String> from List<Integer>, because nothing about T survives compilation at all.',
  keyPoints: ['The runtime class is identical before and after generics', 'The compiler inserts the same cast bytecode either way — generics just make it provably safe', 'Every erasure-related gotcha follows from this one fact'],
  seniorFollowUps: ['Would reified generics (like C#) have been possible to retrofit into Java 5 instead? Why did the JDK team not go that route?'],
  topic: 'java',
  subtopic: 'generics',
  difficulty: 'Intermediate',
  seniority: 'Senior',
  tags: ['generics', 'type-erasure', 'fundamentals'],
},
]
